stages:
  data_cleaning:
    cmd: python swiggy_delivery_time_prediction\data\data_cleaning.py
    deps:
    - data\raw\swiggy.csv
    - swiggy_delivery_time_prediction\data\data_cleaning.py
    outs:
    - data\cleaned\swiggy_cleaned.csv
